version: '3.1'

services:
  postgres:
    image: postgres:9.6.16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_DB: prisma

volumes:
  postgres_data: {}