PHOTON_OUTPUTS = {
    "photonjs": [
        "runtime/highlight/languages/dml.d.ts",
        "runtime/highlight/languages/sql.d.ts",
        "runtime/highlight/highlight.d.ts",
        "runtime/highlight/prism.d.ts",
        "runtime/highlight/theme.d.ts",
        "runtime/highlight/types.d.ts",
        "runtime/utils/common.d.ts",
        "runtime/utils/dedent.d.ts",
        "runtime/utils/deep-extend.d.ts",
        "runtime/utils/deep-set.d.ts",
        "runtime/utils/filterObject.d.ts",
        "runtime/utils/omit.d.ts",
        "runtime/utils/printDatasources.d.ts",
        "runtime/utils/printJsonErrors.d.ts",
        "runtime/utils/printStack.d.ts",
        "runtime/utils/stringifyObject.d.ts",
        "runtime/browser.d.ts",
        "runtime/browser-chalk.d.ts",
        "runtime/browser-terminal-link.d.ts",
        "runtime/dmmf.d.ts",
        "runtime/dmmf-types.d.ts",
        "runtime/error-types.d.ts",
        "runtime/externalToInternalDmmf.d.ts",
        "runtime/getDMMF.d.ts",
        "runtime/index.d.ts",
        "runtime/index.js",
        "runtime/mergeBy.d.ts",
        "runtime/query.d.ts",
        "runtime/transformDmmf.d.ts",
        "runtime/visit.d.ts",
        "index.d.ts",
        "index.js",
        "schema.prisma",
        # How would this be done ?
        # we can use select({}) from Bazel using repository rules
        "runtime/query-engine-debian-openssl-1.1.x",
    ],
}
