filegroup(
    name = "migrations",
    srcs = ["lift.lock"] + glob([
        "**/README.md",
        "**/schema.prisma",
        "**/steps.json",
    ]),
    visibility = ["//examples/prisma:__pkg__"],
)
